export const commentsData = [
    {
        profile: {
            id: '1',
            first: 'Тимур',
            lastname: 'Ульби',
            username: 'admin',
            age: 22,
            currency: 'RUB',
            country: 'Russia',
            city: 'Moscow',
            avatar: 'https://pic.rutubelist.ru/user/3b/27/3b2758ad5492a76b578f7ee072e4e894.jpg',
            email: 'adf@azdaf.ru',
            phone: '13131321321321',
        },
        id: '1',
        text: 'Some comment text',
        profileId: '1',
        articleId: '1',

    },
    {
        profile: {
            id: '2',
            first: 'Иван',
            lastname: 'Иванов',
            username: 'user',
            age: 22,
            currency: 'RUB',
            country: 'Russia',
            city: 'Moscow',
            avatar: 'https://pic.rutubelist.ru/user/3b/27/3b2758ad5492a76b578f7ee072e4e894.jpg',
            email: 'adf@azdkaf.ru',
            phone: '13131321321321',
        },
        id: '2',
        text: 'Some comment text',
        profileId: '2',
        articleId: '1',
    },
];
